--Question 1 answer

SELECT UPPER(cust_first_name || ' ' || cust_last_name) AS customer_name,
       country_id
FROM sh.customers;

--Question 2 answer
DESC SH.PRODUCTS;
SELECT *
FROM SH.PRODUCTS
WHERE ROWNUM = 1;

--Question 3 answer

SELECT prod_name, prod_list_price
FROM sh.products
ORDER BY prod_list_price DESC;

--Question 4  answer
SELECT COUNT(*) AS TOTAL_CUSTOMERS
FROM SH.CUSTOMERS;


--Question 5 answer
SELECT *
FROM SH.CUSTOMERS
WHERE CUST_FIRST_NAME LIKE 'A%';

--Question 6 answer
SELECT CHANNEL_ID,
       SUM(AMOUNT_SOLD) AS TOTAL_SALES
FROM SH.SALES
GROUP BY CHANNEL_ID;

--Question 7 answer
SELECT C.CUST_FIRST_NAME,
       C.CUST_LAST_NAME,
       C.CUST_CITY,
       CO.COUNTRY_NAME
FROM SH.CUSTOMERS C
JOIN SH.COUNTRIES CO
ON C.COUNTRY_ID = CO.COUNTRY_ID;

--Question 8 answer
SELECT CO.COUNTRY_NAME,
       SUM(S.AMOUNT_SOLD) AS TOTAL_SALES
FROM SH.SALES S
JOIN SH.CUSTOMERS C
ON S.CUST_ID = C.CUST_ID
JOIN SH.COUNTRIES CO
ON C.COUNTRY_ID = CO.COUNTRY_ID
GROUP BY CO.COUNTRY_NAME
ORDER BY TOTAL_SALES DESC;

--Question 9 answer
SELECT P.PROD_NAME,
       P.PROD_CATEGORY,
       SUM(S.QUANTITY_SOLD) AS TOTAL_QUANTITY,
       SUM(S.AMOUNT_SOLD) AS TOTAL_REVENUE
FROM SH.SALES S
JOIN SH.PRODUCTS P
ON S.PROD_ID = P.PROD_ID
GROUP BY P.PROD_NAME, P.PROD_CATEGORY
ORDER BY TOTAL_REVENUE DESC;

--Question 10 answer
SELECT *
FROM
(
    SELECT C.CUST_FIRST_NAME,
           C.CUST_LAST_NAME,
           SUM(S.AMOUNT_SOLD) AS TOTAL_REVENUE
    FROM SH.SALES S
    JOIN SH.CUSTOMERS C
    ON S.CUST_ID = C.CUST_ID
    GROUP BY C.CUST_FIRST_NAME, C.CUST_LAST_NAME
    ORDER BY TOTAL_REVENUE DESC
)
WHERE ROWNUM <= 10;