-- Question 11 Answers

SELECT C.CUST_ID,
       C.CUST_FIRST_NAME,
       C.CUST_LAST_NAME,
       C.CUST_CITY,
       C.COUNTRY_ID
FROM SH.CUSTOMERS C
LEFT JOIN SH.SALES S
ON C.CUST_ID = S.CUST_ID
WHERE S.CUST_ID IS NULL;

-- Question 12 answer 
SELECT P.PROD_ID,
       P.PROD_NAME,
       P.PROD_CATEGORY
FROM SH.PRODUCTS P
LEFT JOIN SH.SALES S
ON P.PROD_ID = S.PROD_ID
WHERE S.PROD_ID ;


--Question 13 answer 

SELECT CH.CHANNEL_DESC,
       SUM(S.AMOUNT_SOLD) AS TOTAL_REVENUE,
       SUM(S.QUANTITY_SOLD) AS TOTAL_QUANTITY
FROM SH.SALES S
JOIN SH.CHANNELS CH
ON S.CHANNEL_ID = CH.CHANNEL_ID
GROUP BY CH.CHANNEL_DESC
ORDER BY TOTAL_REVENUE DESC;


-- Question 14 Answer 
SELECT CO.COUNTRY_NAME,
       COUNT(C.CUST_ID) AS TOTAL_CUSTOMERS
FROM SH.COUNTRIES CO
LEFT JOIN SH.CUSTOMERS C
ON CO.COUNTRY_ID = C.COUNTRY_ID
GROUP BY CO.COUNTRY_NAME
ORDER BY TOTAL_CUSTOMERS ASC;


-- Question 15 Answer
SELECT PR.PROMO_NAME,
       SUM(S.AMOUNT_SOLD) AS TOTAL_REVENUE
FROM SH.SALES S
JOIN SH.PROMOTIONS PR
ON S.PROMO_ID = PR.PROMO_ID
GROUP BY PR.PROMO_NAME
HAVING SUM(S.AMOUNT_SOLD) > 100000
ORDER BY TOTAL_REVENUE DESC;


-- Question 16 Answer 
SELECT TIMES.CALENDAR_YEAR,
       SUM(SALES.AMOUNT_SOLD) AS TOTAL_REVENUE
FROM SH.SALES SALES
JOIN SH.TIMES TIMES
ON SALES.TIME_ID = TIMES.TIME_ID
GROUP BY TIMES.CALENDAR_YEAR
ORDER BY TIMES.CALENDAR_YEAR;











































$0